apiVersion: v1
kind: Template
metadata:
  name: amqp-cloud-native-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: amqp-cloud-native-app
    name: amqp-cloud-native-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: amqp-cloud-native-app
    template:
      metadata:
        labels:
          app: amqp-cloud-native-app
      spec:
        containers:
        - image: ${CONTAINER_IMAGE}
          imagePullPolicy: Always
          name: amqp-cloud-native-app
          env:
            # - name:  mp.messaging.outgoing.stock-moves-output.host #both versions work
            - name: MP_MESSAGING_OUTGOING_STOCK_MOVES_OUTPUT_HOST
              valueFrom:
                configMapKeyRef:
                  name:  messaging-config
                  key:  service.host
            # - name:  mp.messaging.incoming.stock-moves-input.host #both versions work
            - name:  MP_MESSAGING_INCOMING_STOCK_MOVES_INPUT_HOST
              valueFrom:
                configMapKeyRef:
                  name:  messaging-config
                  key:  service.host
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 5
          terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: amqp-cloud-native-app
    name: amqp-cloud-native-app
  spec:
    ports:    
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
    selector:
      app: amqp-cloud-native-app
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: amqp-cloud-native-app
    name: amqp-cloud-native-app
  spec:
    to:
      kind: Service
      name: amqp-cloud-native-app
      weight: 100
parameters:
- description: Container image name, including registry url
  displayName: Container image name, including registry url
  required: true
  name: CONTAINER_IMAGE
labels:
  template: amqp-cloud-native-template