apiVersion: v1
kind: Service
metadata:
  name: mongo-database
  labels:
    app: mongo-database
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
      protocol: TCP
  selector:
    app: mongo-database
  type: LoadBalancer