apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: orders-rest-api
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/famargon/orders-rest-api:latest
    generation: 5
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
