apiVersion: v1
kind: List
items:
- apiVersion: enmasse.io/v1beta1
  kind: AddressSpace
  metadata:
    name: warehouse-address-space
    namespace: warehouse
  spec:
    type: standard
    plan: standard-medium
    endpoints:
    - name: messaging
      service: messaging
      expose:
        type: route
        routeServicePort: amqps
        routeTlsTermination: passthrough
      # cert:
      #   provider: openshift
      exports:
      - name: messaging-config
        kind: ConfigMap
    authenticationService:
      name: none-authservice
      # name: standard-authservice
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: warehouse-address-space.orders
    namespace: warehouse
  spec:
    address: orders
    type: queue
    plan: standard-medium-queue
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: warehouse-address-space.processed-orders
    namespace: warehouse
  spec:
    address: processed-orders
    type: topic
    plan: standard-small-topic
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: warehouse-address-space.events
    namespace: warehouse
  spec:
    address: events
    type: multicast
    plan: standard-medium-multicast
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: warehouse-address-space.stocks
    namespace: warehouse
  spec:
    address: stocks
    type: anycast
    plan: standard-medium-anycast
- apiVersion: enmasse.io/v1beta1
  kind: Address
  metadata:
    name: warehouse-address-space.stocks/requests
    namespace: warehouse
  spec:
    address: stocks/requests
    type: topic
    plan: standard-small-topic
# - apiVersion: user.enmasse.io/v1beta1
#   kind: MessagingUser
#   metadata:
#     name: warehouse-address-space.demo-user-sa
#     namespace: warehouse
#   spec:
#     username: system:serviceaccount:warehouse:default
#     authentication:
#       type: serviceaccount
#     authorization:
#     - operations: ["send", "recv"]
#       addresses: ["*"]
- apiVersion: user.enmasse.io/v1beta1
  kind: MessagingUser
  metadata:
    name: warehouse-address-space.demo-user
    namespace: warehouse
  spec:
    username: demo-user
    authentication:
      type: password
      password: ZGVtby11c2Vy
    authorization:
    - operations: ["send", "recv"]
      addresses: ["orders", "processed-orders", "events", "stocks", "*temp.*"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: messaging-config
    namespace: warehouse
  rules:
    - apiGroups: [ "" ]
      resources: [ "configmaps" ]
      verbs: [ "create" ]
    - apiGroups: [ "" ]
      resources: [ "configmaps" ]
      resourceNames: [ "messaging-config" ]
      verbs: [ "get", "update", "patch" ]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: messaging-config
    namespace: warehouse
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: messaging-config
  subjects:
  - kind: ServiceAccount
    name: address-space-controller
    namespace: enmasse-infra